name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build the project
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the project
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 8

    - name: npm install and build
      run: |
        make deps
        make build
